//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressTable
    {
        public int AddressId { get; set; }
        public string streetAddress { get; set; }
        public string City { get; set; }
        public string Contery { get; set; }
        public Nullable<int> PhonNo { get; set; }
        public string FullAddress { get; set; }
    }
}
