//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfDemo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Runtime.CompilerServices;


    public partial class PersonalTable : INotifyPropertyChanged
    {
        private int _personId;
        private string _firstName;
        private string _lastName;
        private int? _age;
        private DateTime? _dateOfBerth;
        private bool? _isActive;
        private decimal? _accountBalance;
        private string _fullName;

        public int PersonId { get => _personId; set {
                PersonId = value;
                OnPropertyChanged(nameof(PersonId));
            }
        }
        public string FirstName { get => _firstName; set
            {
                FirstName = value;
                OnPropertyChanged(nameof(FirstName));
            }
        }
        public string LastName { get => _lastName; set
            {
                LastName = value;
                OnPropertyChanged(nameof(LastName));
            }
        }
        public Nullable<int> Age { get => _age; set
            {
                Age = value;
                OnPropertyChanged(nameof(Age));
            }
        }
        public Nullable<System.DateTime> DateOfBerth { get => _dateOfBerth; set
            {
                DateOfBerth = value;
                OnPropertyChanged(nameof(DateOfBerth));
            }
        }
        public Nullable<bool> IsActive { get => _isActive; set
            {
                IsActive = value;
                OnPropertyChanged(nameof(IsActive));
            }
        }
        public Nullable<decimal> AccountBalance { get => _accountBalance; set => _accountBalance = value; }
        public string FullName { get
            {
                return $"{FirstName}  {LastName}";
            }
        }
        public event PropertyChangedEventHandler PropertyChanged;
        protected void OnPropertyChanged([CallerMemberName]string propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));


        }
    }

}
